### ISSUE TITLE
Assembled Hardware?

### ISSUE THREAD

**Issue by ghost** [amadeuspzs/esp8266-temperature-humidity#5]
The hardware you've designed here is exactly what I'm looking for to complete a project.

Curiously, do you have this printed and assembled by a 'factory' or are you doing it by hand?

**Comment by amadeuspzs** [comment]
Hi @msoose I print it with jlcpcb.com which is really straightforward.

I've then hand soldered the boards (the QFN package for the Si7021 is a little tricky and an earlier PCB design had extended pads to help - I will add this back in in future, but you can still hand solder the current PCB).

I've also rigged up a clothes iron to solder with a stencil (also from jlcpcb) and paste which works really well: https://twitter.com/amadeuspzs/status/1372111453885505539

I looked into a full assembly but didn't find a supplier with all the components I've selected. In future I might start with their components first if I want to scale up (e.g. https://jlcpcb.com/parts)
